### PR TITLE
Fix guild chatbox width

### PR DESCRIPTION
**Pull request by KaKi87**
Preview :

| Before  | After |
| ------------- | ------------- |
| 2020-04-06 11_33_56-Paramètres 2020-04-06 11_34_50-Paramètres | 2020-04-06 11_40_35-Paramètres |

Target element :

2020-04-06 11_48_40-Developer Tools - https___discordapp com_channels_@me_493524617714204672
2020-04-06 11_48_03-Paramètres

Very nice project, keep it up ! 💪

### CODE REVIEW

**Comment by Gibbu** [comment]
Hey cheers mate. I recently moved all my themes back to my original repo as I was testing an org and didn't really like it.
Old repo: https://github.com/Gibbu/BetterDiscord-Themes/tree/master/Slate

**Comment by KaKi87** [comment]
Hey,

> I recently moved all my themes back to my original repo as I was testing an org and didn't really like it.

Well, since absolutely everyone use a single repo with folders containing plugins and themes mixed together, and doesn't use any other solution, I suppose there might be a reason, but I can't find it. What is it ?

I only see disadvantages of doing this : mixed commit history, no proper versioning and release management, mixed issues, etc.

> Also, when updating a .scss file you'll also need to re-add the entire compiled css to the base.css file.

I thought that you would like contributors to edit the SCSS instead of modifying the "compiled" one, and then you would "compile the modified file" into a production file.
Personally, I don't like to use these kind of stuff.

**Comment by Gibbu** [comment]
> why did you abandoned the bottom left style ?  

At the moment the bottom left is still in progress. I'm not sure what I want to do with it. I did like the mute/deafen/settings buttons being extended but didn't really like the connect voice channel buttons as they were too long in my opinion.

> I only see disadvantages of doing this : mixed commit history, no proper versioning and release management, mixed issues, etc.

I wanted to try and org but I didn't like that I had to open different folders(repos) to push updates and the mixed commit history/issues doesn't bother me at all.

**Comment by KaKi87** [comment]
> the mixed commit history/issues doesn't bother me at all

And, mixed pull requests, too.

**Pull request closed without merging**
